security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
          algorithm: bcrypt

    providers:
        # Default value before edit
        # in_memory: { memory: ~ }
        my_provider:
          entity:
            class: App\Entity\User
            property: email #we can use email instead

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            form_login:
              login_path: login
              check_path: login
              provider: my_provider
              default_target_path: login_success
              always_use_default_target_path: true

            logout:
              path: logout
              target: login

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetpass$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_success$, roles: [ROLE_CUSTOM, ROLE_PARENT, ROLE_ADMIN] }
        - { path: ^/account$, roles: [ROLE_PARENT, ROLE_ADMIN] }
        - { path: ^/account/, roles: [ROLE_PARENT, ROLE_ADMIN] }
        - { path: ^/smartpay/, roles: [ROLE_PARENT, ROLE_ADMIN] }
        - { path: ^/smartpay_proof/, roles: [ROLE_PARENT, ROLE_ADMIN] }
        - { path: ^/smartpay_prfrem/, roles: [ROLE_PARENT, ROLE_ADMIN] }
        - { path: ^/smart_receipt_pdf/, roles: [ROLE_PARENT, ROLE_ADMIN] }
        - { path: ^/$, roles: [ROLE_CUSTOM,ROLE_PARENT,ROLE_ADMIN] }
        - { path: ^/, roles: [ROLE_CUSTOM, ROLE_ADMIN] }
