#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#
#    can use the following if we want a default controller defined:
#    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction

index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'home.page.html.twig'
