#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#
#    can use the following if we want a default controller defined:
#    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction

# using controller route right now.
# login:
#   path: /login
#   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#   defaults:
#     template: 'security/login.html.twig'
