#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#
#    can use the following if we want a default controller defined:
#    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction

login:
  path: /login
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'login.html.twig'
